-- 500 PM Interview Questions (5 categories × 100)
-- Run in Supabase SQL Editor or via: supabase db execute --file supabase/questions_600.sql

insert into questions (question, category, difficulty, question_type) values

-- ============================================================
-- PRODUCT DESIGN (100) → product_sense
-- ============================================================
('For a retail store, users are frequently complaining about long queues during checkout. What strategy would you use to improve the experience in the short term and long term?', 'product_sense', 'medium', 'improve'),
('How would you build a product on Facebook for blood donation?', 'product_sense', 'medium', 'design'),
('How would you design a "Google Refrigerator"?', 'product_sense', 'medium', 'design'),
('Explain some new Alexa skillsets you would roll out and why.', 'product_sense', 'easy', 'design'),
('Design an application launching in the US marketplace that enables patients to find doctors.', 'product_sense', 'medium', 'design'),
('Design an experience for getting book recommendations on Facebook. How would you measure success?', 'product_sense', 'medium', 'design'),
('You are a new PM at Google Pay. Design a feature for paying credit card bills.', 'product_sense', 'medium', 'design'),
('What innovative new product can make park gatherings be more social, with strangers?', 'product_sense', 'easy', 'design'),
('Design a vending machine for blind people.', 'product_sense', 'medium', 'design'),
('How would you go about designing a skip feature for a video streaming service?', 'product_sense', 'easy', 'design'),
('As a Product Manager on Facebook Newsfeed, how would you decide whether to show an advertisement or the "People You May Know" widget?', 'product_sense', 'hard', 'prioritize'),
('How would you design a gardening app?', 'product_sense', 'easy', 'design'),
('Design a digital payments system for rural India.', 'product_sense', 'hard', 'design'),
('Design a fridge for kids.', 'product_sense', 'easy', 'design'),
('How would you design an ETA system for Lyft drivers?', 'product_sense', 'medium', 'design'),
('Design Lyft for kids.', 'product_sense', 'medium', 'design'),
('Design a driverless car pick-up service for kids.', 'product_sense', 'medium', 'design'),
('Design a better way to find a roommate in a new city.', 'product_sense', 'medium', 'design'),
('Design a refrigerator for the blind.', 'product_sense', 'medium', 'design'),
('Design a washing machine for Google.', 'product_sense', 'medium', 'design'),
('Design a Facebook tool for the Olympics.', 'product_sense', 'medium', 'design'),
('Build a Google product that enables people to learn new skills.', 'product_sense', 'medium', 'design'),
('Design dynamic pricing for Lyft.', 'product_sense', 'hard', 'design'),
('How would you go about designing a dashboard of call quality for WhatsApp?', 'product_sense', 'medium', 'design'),
('Create a smartphone for a 6-year-old.', 'product_sense', 'medium', 'design'),
('Google wants to venture in the large appliances industry starting with a refrigerator. As a PM in Google, how would you go about designing a Smart Refrigerator for the USA?', 'product_sense', 'hard', 'design'),
('Design an ATM for airports.', 'product_sense', 'medium', 'design'),
('Design a referral system for a grocery app.', 'product_sense', 'medium', 'design'),
('How would you redesign the carwash?', 'product_sense', 'easy', 'improve'),
('Imagine you''re a PM at Meta. How would you make users feel less guilty about using Instagram while also increasing revenue?', 'product_sense', 'hard', 'design'),
('Design a cab-sharing service inside a chat application.', 'product_sense', 'medium', 'design'),
('How would you design Google Maps for kids?', 'product_sense', 'medium', 'design'),
('Design a fridge for a person in a wheelchair.', 'product_sense', 'medium', 'design'),
('How would you design a new music experience for Facebook?', 'product_sense', 'medium', 'design'),
('Design a photo app for the blind.', 'product_sense', 'medium', 'design'),
('Design a product for teenagers to have more empathy.', 'product_sense', 'hard', 'design'),
('How would you design a phone for kids aged less than 5 years?', 'product_sense', 'medium', 'design'),
('Design a bookshelf for kids.', 'product_sense', 'easy', 'design'),
('Design a product to improve the lunch experience in XYZ company.', 'product_sense', 'easy', 'design'),
('Design an alarm clock for the blind.', 'product_sense', 'medium', 'design'),
('Create a way to sell movie tickets on Facebook.', 'product_sense', 'medium', 'design'),
('Design a loyalty program for a search engine that''s competing with Google & Bing.', 'product_sense', 'hard', 'design'),
('Design an alarm clock for elderly people.', 'product_sense', 'medium', 'design'),
('Build a new product on Facebook to find apartments.', 'product_sense', 'medium', 'design'),
('Google is working on a tech that allows people to travel from SF to Seattle in just 15 minutes for only $1000 per person, one way. What would you do with this tech?', 'product_sense', 'hard', 'strategy'),
('You are a new PM at Facebook. Design an app to help people save money.', 'product_sense', 'medium', 'design'),
('Design an app for the DMV (California''s Department of Motor Vehicles).', 'product_sense', 'medium', 'design'),
('As a product manager, how would you design a communication solution for use by astronauts on a mission to Mars landing?', 'product_sense', 'hard', 'design'),
('Design a multi-factor authentication app for the visually challenged.', 'product_sense', 'medium', 'design'),
('Design WhatsApp for children.', 'product_sense', 'medium', 'design'),
('How would you create a playlist for a user after they listen to a single song (in an app like Spotify)?', 'product_sense', 'medium', 'design'),
('How would you design a cafeteria app for employees?', 'product_sense', 'easy', 'design'),
('Design a product to fight climate change.', 'product_sense', 'hard', 'design'),
('You''re a PM at a vending machine company. Your CEO asks you to design a new line of vending machines to be placed in hotels and motels. What would you do?', 'product_sense', 'medium', 'design'),
('Design a touchscreen table for restaurants.', 'product_sense', 'medium', 'design'),
('How would you improve Grammarly? Should Google acquire Grammarly?', 'product_sense', 'hard', 'improve'),
('Design an app for making someone a better cook.', 'product_sense', 'easy', 'design'),
('What feature would you add to a self-driving car to make it a more attractive purchase?', 'product_sense', 'medium', 'design'),
('Design an app for an amusement park.', 'product_sense', 'easy', 'design'),
('Design a healthcare application that would be useful for handling COVID-19.', 'product_sense', 'hard', 'design'),
('Design a meditation app for kids.', 'product_sense', 'easy', 'design'),
('Design a product to find a handyman.', 'product_sense', 'easy', 'design'),
('Design a task assignment form for an app.', 'product_sense', 'easy', 'design'),
('How would you improve the experience of a customer visiting your physical retail store?', 'product_sense', 'medium', 'improve'),
('Design a data center on the moon for Google.', 'product_sense', 'hard', 'design'),
('The CEO of your company asks you to design a new ATM for their airport segment. What do you do?', 'product_sense', 'medium', 'design'),
('Redesign a patrol station.', 'product_sense', 'medium', 'improve'),
('You are a product manager at a start-up whose technology can detect emotions. Evaluate potential applications.', 'product_sense', 'hard', 'strategy'),
('How would you design a product for improving teenage health?', 'product_sense', 'medium', 'design'),
('Design a Facebook product for organ donation.', 'product_sense', 'medium', 'design'),
('Design a product to choose cheese.', 'product_sense', 'easy', 'design'),
('Design Lyft for delivery.', 'product_sense', 'medium', 'design'),
('Design a Google bicycle.', 'product_sense', 'medium', 'design'),
('Design an Instagram feature to help people find a restaurant.', 'product_sense', 'medium', 'design'),
('Mark has asked you to build a new app for wine shopping in a grocery store. What do you do?', 'product_sense', 'medium', 'design'),
('Design a blender for the visually impaired.', 'product_sense', 'medium', 'design'),
('Design a product for child care.', 'product_sense', 'medium', 'design'),
('Design an online store to sell bicycles to 12-year-old girls.', 'product_sense', 'medium', 'design'),
('As a PM at Apple, how would you reduce accidents with smartphones?', 'product_sense', 'hard', 'design'),
('Design a product to buy flight tickets.', 'product_sense', 'medium', 'design'),
('Build a product to buy and sell antiques.', 'product_sense', 'medium', 'design'),
('How would you design a bicycle renting app for tourists?', 'product_sense', 'easy', 'design'),
('How would you design a web search engine for children below 14 years old?', 'product_sense', 'medium', 'design'),
('How would you improve Outlook for the use case when people get overwhelmed by number of emails received after returning from a vacation?', 'product_sense', 'medium', 'improve'),
('Build a product to solve the dog poop problem.', 'product_sense', 'easy', 'design'),
('Design a Supermarket for older people.', 'product_sense', 'medium', 'design'),
('How would you prevent hate, misinformation or deepfakes on YouTube?', 'product_sense', 'hard', 'design'),
('Design a library for the future.', 'product_sense', 'medium', 'design'),
('How would you improve Facebook Groups?', 'product_sense', 'medium', 'improve'),
('How would you design a consumer application for a scooter sharing business?', 'product_sense', 'medium', 'design'),
('How would you design a car sharing platform like Uber for disabled people?', 'product_sense', 'hard', 'design'),
('How would you go about designing a new location sharing app for Google?', 'product_sense', 'medium', 'design'),
('Design a product for Facebook to fight COVID-19.', 'product_sense', 'medium', 'design'),
('Design Netflix for Senior Citizens (Goal: Increase engagement time).', 'product_sense', 'medium', 'design'),
('Design a social travel product.', 'product_sense', 'medium', 'design'),
('Design a product for event gathering for Google.', 'product_sense', 'medium', 'design'),
('How would you improve Facebook Pay?', 'product_sense', 'medium', 'improve'),
('How would you design an app to help people choose which cheese to buy at a grocery store?', 'product_sense', 'easy', 'design'),
('Design a product for job seekers to create resumes and find the best matching jobs easily and quickly.', 'product_sense', 'medium', 'design'),
('Design Uber for kids.', 'product_sense', 'medium', 'design'),

-- ============================================================
-- DATA & METRICS (100) → metrics
-- ============================================================
('What metrics would you use to measure the success of the Save feature at Facebook?', 'metrics', 'medium', 'metrics'),
('How would you measure the success of Facebook Likes?', 'metrics', 'medium', 'metrics'),
('What metrics would you look at as a product manager for Instagram ads?', 'metrics', 'medium', 'metrics'),
('You launched a new feature that determines whether a Facebook message was read by a recipient. What metrics would you collect? How would you know the feature was a success?', 'metrics', 'medium', 'metrics'),
('Identify one metric for Facebook Marketplace that the whole team should monitor daily.', 'metrics', 'easy', 'metrics'),
('What is the most important metric for Google Docs and why?', 'metrics', 'easy', 'metrics'),
('What is the most important metric for Uber Eats? Why?', 'metrics', 'easy', 'metrics'),
('What success metrics would you use to measure a payment gateway product?', 'metrics', 'medium', 'metrics'),
('What metrics would you use to track the improvement of sense of community within Facebook Groups?', 'metrics', 'medium', 'metrics'),
('How do you measure success of the Facebook Fundraising feature?', 'metrics', 'medium', 'metrics'),
('Around 40% of reviews in Amazon are fake. As a PM in Amazon, how will you tackle the problem? Break your answer into 3 parts — How will you identify a review is fake? What action will you take? If the number of fake reviews are decreased, what will be the impact?', 'metrics', 'hard', 'diagnosis'),
('You are PM of FB Events and you saw an overnight drop in RSVPs by 10%. How would you go about determining what happened?', 'metrics', 'hard', 'diagnosis'),
('What are the success metrics for Facebook Live at the growth phase?', 'metrics', 'medium', 'metrics'),
('How would you measure the success of Google Photos?', 'metrics', 'medium', 'metrics'),
('You are the PM of Instagram Stories. What goal would you set and how would you measure success?', 'metrics', 'medium', 'metrics'),
('What goals would you set for a Facebook Dating feature?', 'metrics', 'medium', 'metrics'),
('How would you evaluate the success of Instagram Stories?', 'metrics', 'medium', 'metrics'),
('How would you measure the success of Gmail?', 'metrics', 'medium', 'metrics'),
('You are the PM of the Facebook timeline. How would you measure retention?', 'metrics', 'hard', 'metrics'),
('How would you evaluate the success of Reactions in Facebook?', 'metrics', 'medium', 'metrics'),
('You''re the PM for Facebook Pay. What goals would you define and what metrics would you track to measure your team''s success?', 'metrics', 'hard', 'metrics'),
('How would you measure the success of Uber Ride?', 'metrics', 'medium', 'metrics'),
('How do you define success for Yelp reviews?', 'metrics', 'medium', 'metrics'),
('Imagine you were in charge of Facebook Watch. What metric would you want to measure?', 'metrics', 'easy', 'metrics'),
('You are a PM for an e-commerce company. The data team lost all key metrics. What metrics will you track as PM?', 'metrics', 'hard', 'metrics'),
('You are the PM of Facebook Lite. What goals would you set?', 'metrics', 'medium', 'metrics'),
('How would you measure the success of Google Calendar?', 'metrics', 'medium', 'metrics'),
('You are the PM who launched Instagram videos. What would be the goals and the success metrics?', 'metrics', 'medium', 'metrics'),
('What metrics would you look at to evaluate LinkedIn''s success?', 'metrics', 'medium', 'metrics'),
('You are the PM in charge of Facebook Reactions. What would success look like in terms of number of non-like reactions per post at launch, and how do you come up with this? Would this number differ by reaction? Why or why not?', 'metrics', 'hard', 'metrics'),
('Users have decision fatigue on Uber Eats. What success metrics would you use to check the impact?', 'metrics', 'medium', 'metrics'),
('How should you decide whether to autoplay videos on the newsfeed? What are the metrics for success?', 'metrics', 'medium', 'metrics'),
('Late deliveries lead to customer churn. What data should we look at to prove this hypothesis for a food delivery app?', 'metrics', 'medium', 'metrics'),
('How would you measure the success of YouTube?', 'metrics', 'medium', 'metrics'),
('How would you determine success for the Facebook profile verification checkmark?', 'metrics', 'medium', 'metrics'),
('What is the most important metric for Slack and why?', 'metrics', 'easy', 'metrics'),
('How would you measure the success of Uber Grocery?', 'metrics', 'medium', 'metrics'),
('You are the PM of the "Share" feature on Facebook. How would you measure the success of this feature?', 'metrics', 'easy', 'metrics'),
('How would you go about setting goals for Instagram hashtags?', 'metrics', 'medium', 'metrics'),
('How would you measure the performance and health of a Netflix Original?', 'metrics', 'hard', 'metrics'),
('You''re the PM for a new Meta product called Audio Rooms. What goals would you set for this product?', 'metrics', 'medium', 'metrics'),
('Pick a feature from a product of your choice and tell us how you will assess the success of that feature. Assume it is being launched now.', 'metrics', 'medium', 'metrics'),
('You are a PM for Facebook Events focused on growth. What would be your North Star metric?', 'metrics', 'medium', 'metrics'),
('Consider LinkedIn. Which are the top three metrics you would check first thing in the morning?', 'metrics', 'medium', 'metrics'),
('How would you measure improvements made to Facebook Messenger?', 'metrics', 'medium', 'metrics'),
('You are the PM for Amazon''s cart page. How would you build a dashboard to measure success?', 'metrics', 'hard', 'metrics'),
('How would you measure the success of the Netflix recommendation engine?', 'metrics', 'hard', 'metrics'),
('How would you set the goal for Facebook''s Crisis Response feature?', 'metrics', 'hard', 'metrics'),
('You are part of Reddit''s product management team. How would you measure the success of Reddit?', 'metrics', 'medium', 'metrics'),
('If you were the PM for Lyft, what dashboard would you build to track the health of the app?', 'metrics', 'hard', 'metrics'),
('How would you measure the success of Facebook Friends feature?', 'metrics', 'easy', 'metrics'),
('Set goals for Facebook notifications.', 'metrics', 'medium', 'metrics'),
('Instagram is launching video calling. How would you test and measure its success?', 'metrics', 'medium', 'metrics'),
('You are the PM for Facebook/Instagram. You want to add a "Mute showing food" feature. How would you measure success?', 'metrics', 'medium', 'metrics'),
('You are the PM for Facebook Pages. What features would you prioritize?', 'metrics', 'medium', 'metrics'),
('What metrics would you track if you were PM of Facebook Birthdays?', 'metrics', 'easy', 'metrics'),
('What do you think is the most important metric to track in Google Search and why?', 'metrics', 'medium', 'metrics'),
('How do you define the goals and metrics for Facebook Newsfeed?', 'metrics', 'hard', 'metrics'),
('What are the important metrics a PM for a luxury goods e-commerce website should look at?', 'metrics', 'medium', 'metrics'),
('How would you change the Amazon Fresh experience and how would you measure success?', 'metrics', 'hard', 'metrics'),
('Which metrics would you track for Uber Pool during the first 6 months after product launch?', 'metrics', 'medium', 'metrics'),
('What metrics would you choose for TikTok Live?', 'metrics', 'medium', 'metrics'),
('What metrics would you use to measure notifications at Facebook?', 'metrics', 'medium', 'metrics'),
('What metrics do you think are most important for evaluating the success of Facebook''s Workplace product?', 'metrics', 'medium', 'metrics'),
('What goals would you set for Instagram Reels, as an Instagram Reels product manager?', 'metrics', 'hard', 'metrics'),
('What would be the top six metrics for WhatsApp? Now pick one from the six. Tell me three things you would do to improve that metric.', 'metrics', 'hard', 'metrics'),
('How would you find if a customer is brand agnostic or not when shopping?', 'metrics', 'hard', 'diagnosis'),
('Facebook is running a test where they hide the like/comment/share bar of each Newsfeed post. What metrics do you expect to move, and how would you decide to roll out the feature?', 'metrics', 'hard', 'metrics'),
('How would you define success for Facebook Shops?', 'metrics', 'medium', 'metrics'),
('How would you describe and assess how the Uber Marketplace (matching platform) is doing, for UberX?', 'metrics', 'hard', 'metrics'),
('Make an argument for offering some free storage space to Google Photos users.', 'metrics', 'hard', 'strategy'),
('Define the metrics for YouTube search.', 'metrics', 'medium', 'metrics'),
('Instagram recently decided to hide like counts on posts. How would you measure the success of this feature?', 'metrics', 'medium', 'metrics'),
('Facebook''s DAU is decreasing 15% per week for the last 3 weeks. How would you find out why?', 'metrics', 'hard', 'diagnosis'),
('Facebook is launching a money transfer feature. What would you choose as success metrics?', 'metrics', 'medium', 'metrics'),
('What metrics would you track to increase the content consumption of Spotify by 10x?', 'metrics', 'hard', 'metrics'),
('How do you measure the success of Google Search?', 'metrics', 'medium', 'metrics'),
('Set goals for Facebook Stories.', 'metrics', 'medium', 'metrics'),
('What data points would you track to know if a Zoom meeting was successful or not?', 'metrics', 'medium', 'metrics'),
('What goals would you set for Facebook Jobs?', 'metrics', 'medium', 'metrics'),
('How do you measure the success of the Hot Home feature in Redfin?', 'metrics', 'medium', 'metrics'),
('What are the key metrics to capture for a streaming service product?', 'metrics', 'medium', 'metrics'),
('You are the PM for privacy and security at Facebook. What goal would you set and how would you measure success?', 'metrics', 'hard', 'metrics'),
('Suppose you''re the Chief Product Officer of Swiggy. What are the top three metrics you would track?', 'metrics', 'hard', 'metrics'),
('Imagine you are the head of Product at Airbnb. What top 2–3 metrics would you monitor?', 'metrics', 'medium', 'metrics'),
('How would you test LinkedIn''s "People you may know" when you don''t have any data to base decisions on?', 'metrics', 'hard', 'metrics'),
('Facebook is changing the composer UI to a "+" button at the bottom. How would you test if this is a good idea?', 'metrics', 'medium', 'metrics'),
('How do you measure the success of Airbnb Online Experiences?', 'metrics', 'medium', 'metrics'),
('Facebook wants to split its News Feed into two. What metrics would you look at to validate this decision?', 'metrics', 'hard', 'metrics'),
('As PM for Instagram Stories, you''re considering increasing the story expiration time. What metrics would you use to decide?', 'metrics', 'hard', 'metrics'),
('How do you measure the success of Instacart?', 'metrics', 'medium', 'metrics'),
('You launched a new Facebook feature with 20% engagement. How will you know if overall Facebook engagement increased, decreased, or stayed the same?', 'metrics', 'hard', 'metrics'),
('If you were to build Facebook Events from scratch, how would you measure success?', 'metrics', 'medium', 'metrics'),
('How would you measure the success of Google Hangouts?', 'metrics', 'medium', 'metrics'),
('How would you assess the opportunity for showing a "You may also like" block alongside the ads block on Google Shopping?', 'metrics', 'hard', 'metrics'),
('How would you measure the success of Zoom?', 'metrics', 'medium', 'metrics'),
('Pick your favorite product and, as PM, define the daily dashboard you''d use to run the business.', 'metrics', 'hard', 'metrics'),
('An Instagram A/B test shows +10% Stories usage but −10% overall usage. What metrics would you request to make the trade-off decision?', 'metrics', 'hard', 'diagnosis'),
('As PM for Facebook News Feed, you aim to increase posts seen per day. Which metrics would be affected, and what data would you expect?', 'metrics', 'hard', 'metrics'),
('Imagine you are PM of Uber''s search map. How would you calculate its success?', 'metrics', 'medium', 'metrics'),

-- ============================================================
-- PROBLEM SOLVING (100) → execution
-- ============================================================
('A metric for a video streaming service dropped by 80%. What do you do?', 'execution', 'hard', 'diagnosis'),
('Your new feature boosts Amazon Search by 10% but adds 2 seconds to load time. What do you do?', 'execution', 'hard', 'problem_solving'),
('Drivers are dropping out of a city on Lyft. How do you figure out what''s going on?', 'execution', 'medium', 'diagnosis'),
('There is a 15% drop in Instagram app open rate. You are the PM — what could have happened?', 'execution', 'medium', 'diagnosis'),
('You launched a new signup flow: profile info ↑8% but 7-day retention ↓2%. What do you do?', 'execution', 'hard', 'problem_solving'),
('Data shows more Uber airport drop-offs than pick-ups. Why, and what would you change in product?', 'execution', 'medium', 'diagnosis'),
('New patients are not showing up for their first telehealth appointment. How do you solve this?', 'execution', 'medium', 'problem_solving'),
('You notice a spike in user-uploaded videos on your platform in June. What''s the cause? How do you test it?', 'execution', 'medium', 'diagnosis'),
('You are the PM of Instagram. MAU constant, DAU declined. What do you do?', 'execution', 'hard', 'diagnosis'),
('Weekly active users (WAU) for iPhone app dropped. What happened?', 'execution', 'medium', 'diagnosis'),
('How would you reduce cancellations for Uber?', 'execution', 'medium', 'problem_solving'),
('What are your solutions to reduce car cancellation rate on Uber''s waiting page?', 'execution', 'medium', 'problem_solving'),
('New users signing up for Facebook are not returning after 30 days. How do you identify the problem?', 'execution', 'medium', 'diagnosis'),
('Facebook Stories engagement ↑ but Newsfeed engagement ↓. What do you do?', 'execution', 'hard', 'problem_solving'),
('Imagine you are a PM at Amazon. How would you reduce product return rates?', 'execution', 'medium', 'problem_solving'),
('There has been a 15% drop in usage of Facebook Groups. How would you fix it?', 'execution', 'medium', 'diagnosis'),
('Daily active users on Instagram have dropped by 20%. What steps do you follow to identify the root cause?', 'execution', 'medium', 'diagnosis'),
('There are ~1 million inactive Netflix users. What would you do?', 'execution', 'medium', 'problem_solving'),
('Facebook Messenger usage is down. Figure out why and what you would do.', 'execution', 'medium', 'diagnosis'),
('You are a PM at a hyperlocal grocery delivery startup. High returns on rice orders — what are your hypotheses, and how do you solve this?', 'execution', 'medium', 'problem_solving'),
('You walk into the office and find that Google Cloud subscriptions have dropped by 20%. What do you do?', 'execution', 'hard', 'diagnosis'),
('You are a PM for LinkedIn Trust Team. Senior influencers complain about spam connection requests and threaten to leave. What do you do?', 'execution', 'hard', 'problem_solving'),
('How would you increase customer lifetime value (CLV) for Swiggy?', 'execution', 'hard', 'problem_solving'),
('You are the new PM for a crypto exchange. Set a product roadmap and define core metrics for the first 18 months.', 'execution', 'hard', 'problem_solving'),
('Google Maps daily active users dropped 10%. What do you do?', 'execution', 'medium', 'diagnosis'),
('Order cancellations increased by 15%. How do you diagnose the root cause?', 'execution', 'medium', 'diagnosis'),
('Walmart''s order return rate is increasing. What would you look into to isolate the problem?', 'execution', 'medium', 'diagnosis'),
('If Uber Eats orders are down, how will you track the root cause?', 'execution', 'medium', 'diagnosis'),
('Wrong order deliveries increased by 30% for a fashion e-commerce company. How would you identify the root cause and fix it?', 'execution', 'medium', 'diagnosis'),
('There is an 8% drop in Google Search usage. What would you do?', 'execution', 'medium', 'diagnosis'),
('Creation of Facebook user groups is down 20%. What do you do?', 'execution', 'medium', 'diagnosis'),
('There is a 50% drop in Uber rides per day. Diagnose the problem.', 'execution', 'hard', 'diagnosis'),
('You are a PM at Uber or Ola. You need to upsell Uber Go to Uber Auto customers. What product changes would you make?', 'execution', 'medium', 'problem_solving'),
('Large numbers of drivers are dropping out of a particular city. Why might this be?', 'execution', 'medium', 'diagnosis'),
('Facebook Ads dropped by 20%. Mark Zuckerberg calls you — what do you do?', 'execution', 'hard', 'diagnosis'),
('Google Search revenue has gone down. Figure out why.', 'execution', 'hard', 'diagnosis'),
('Paytm transactions dropped by 50% last week. What could be the reasons?', 'execution', 'medium', 'diagnosis'),
('Spotify installs increased by 25%. What are at least four possible reasons?', 'execution', 'medium', 'diagnosis'),
('Suppose you are a PM at Zomato. Office colleagues order from multiple restaurants, causing staggered deliveries and poor experience. How would you solve this?', 'execution', 'medium', 'problem_solving'),
('A Facebook survey shows satisfaction is 30% lower for users with added login security features vs. those without. Why might this be? Comment on survey design.', 'execution', 'hard', 'diagnosis'),
('Utilization dropped 45% on app XYZ in Italy for August. Why, and what''s your fix plan?', 'execution', 'hard', 'diagnosis'),
('Users on Amazon''s site dropped 10%. What are possible reasons and fixes?', 'execution', 'medium', 'diagnosis'),
('Instagram: Stories engagement is up, but feed post engagement is down. What do you do?', 'execution', 'medium', 'diagnosis'),
('20% of Slack extension users uninstalled in one day. What are your assumptions and root-cause steps?', 'execution', 'hard', 'diagnosis'),
('Food-delivery app shows a downward trend in orders fulfilled. How would you find the root cause?', 'execution', 'medium', 'diagnosis'),
('How do you convert offline retail customers to omnichannel/online transactors?', 'execution', 'hard', 'problem_solving'),
('You''re on Internal Audit. What KPIs would you set to measure compliance and risk appetite?', 'execution', 'hard', 'problem_solving'),
('Customers tweet that your waitlist feature shows wrong wait times. How do you investigate?', 'execution', 'medium', 'problem_solving'),
('B2B payment card usage on e-commerce suddenly dropped in April. Analyze and propose solutions.', 'execution', 'hard', 'diagnosis'),
('Friend requests are down 10%. Diagnose.', 'execution', 'medium', 'diagnosis'),
('70% of shoppers view the returns policy before shopping. What do you do?', 'execution', 'medium', 'problem_solving'),
('How would you address homelessness in downtown San Francisco?', 'execution', 'hard', 'problem_solving'),
('Facebook group creation has dropped. Why?', 'execution', 'medium', 'diagnosis'),
('Apple Card customers are missing payments, causing account issues and complaint spikes. Why, and what happens to accounts?', 'execution', 'hard', 'diagnosis'),
('Messenger DAU dropped significantly. How do you find the root cause?', 'execution', 'medium', 'diagnosis'),
('Facebook Page creation fell 10%; you fixed it, but WAU then fell 5%. What next?', 'execution', 'hard', 'problem_solving'),
('Medium''s % active users suddenly dropped 35% after 3 weeks of fluctuation. How do you diagnose and restore?', 'execution', 'hard', 'diagnosis'),
('A grocery brand isn''t selling; inventory is nearing expiry. List reasons and solutions.', 'execution', 'medium', 'problem_solving'),
('Disney+ "Recommended for you" sees a sudden 10% drop in average minutes viewed. What do you do?', 'execution', 'hard', 'diagnosis'),
('Amazon MAU has risen for 6 months, but average sales per user keeps falling. Why?', 'execution', 'hard', 'diagnosis'),
('Flipkart''s revenue metrics recently dropped. What''s the reason?', 'execution', 'medium', 'diagnosis'),
('YouTube revenue suddenly dropped 10%. Why?', 'execution', 'medium', 'diagnosis'),
('You launched a pilot. Now there''s a competing priority: a new feature request vs. a bug fix. How do you decide?', 'execution', 'medium', 'problem_solving'),
('Rider experience with airport rides is worsening. What do you do?', 'execution', 'medium', 'problem_solving'),
('Returns in Flipkart''s mobile category have been rising steadily for 3 months. What''s your approach?', 'execution', 'medium', 'diagnosis'),
('Housing.com mobile leads conversion dropped 3% in 2 weeks. How do you analyze?', 'execution', 'medium', 'diagnosis'),
('As PM for Facebook Live, usage is down 20%. How do you find the root cause?', 'execution', 'medium', 'diagnosis'),
('How would you approach adding an e-commerce "Shop" feature to a subscription product?', 'execution', 'hard', 'problem_solving'),
('Messenger DAU dropped 10%. Why?', 'execution', 'medium', 'diagnosis'),
('During the pandemic, with contracts already signed, how do you deliver projects?', 'execution', 'hard', 'problem_solving'),
('If you had unlimited resources to fix one world problem, what would it be? Who''s your team, and what''s your success metric?', 'execution', 'hard', 'problem_solving'),
('You''re PM for Facebook Likes. Acceptance dropped 5%. What do you do?', 'execution', 'medium', 'diagnosis'),
('What would you do if your web traffic dropped by 100% suddenly?', 'execution', 'hard', 'diagnosis'),
('Airbnb sees more mobile web than native app usage. Why, and what product changes would you make?', 'execution', 'medium', 'diagnosis'),
('Facebook''s new feed algorithm led to a 20% drop in session duration. What do you do?', 'execution', 'hard', 'problem_solving'),
('How would you increase the average Uber driver rating in your area from 4.5?', 'execution', 'medium', 'problem_solving'),
('Uber''s ride rating is 20% below industry standard. How do you fix it?', 'execution', 'medium', 'problem_solving'),
('Pick your favorite product. What one missing feature would make life simpler?', 'execution', 'easy', 'problem_solving'),
('How would you pack and ship exactly 1 lb of apples?', 'execution', 'easy', 'problem_solving'),
('Lyft ride cancellations spiked this week. Why could this be?', 'execution', 'medium', 'diagnosis'),
('At a food delivery firm, lunch conversion is 2% vs. 10% at breakfast/dinner. How would you solve this?', 'execution', 'medium', 'problem_solving'),
('How would you increase Swiggy''s revenue 4x?', 'execution', 'hard', 'problem_solving'),
('How would you regain lost Amazon sellers without increasing budget?', 'execution', 'hard', 'problem_solving'),
('How would you triage a 10% drop in rider cancellations?', 'execution', 'medium', 'diagnosis'),
('As PM for Facebook Friends, friending dropped 5% in a week. Why?', 'execution', 'medium', 'diagnosis'),
('As Amazon seller PM, how would you reactivate churned sellers with budget constraints?', 'execution', 'hard', 'problem_solving'),
('Identify 3–5 issues in a collaborative group lending & savings platform.', 'execution', 'medium', 'problem_solving'),
('Users stopped signing up due to an issue in the sign-up flow. What would you do?', 'execution', 'medium', 'problem_solving'),
('As a new e-commerce player, a customer requests a return past expiration. What would you do?', 'execution', 'easy', 'problem_solving'),
('Zoom integrates AI notes, and meetings decrease. What would you do?', 'execution', 'hard', 'problem_solving'),
('Facebook Marketplace sales are up, but Local Ads revenue is down. Why?', 'execution', 'hard', 'diagnosis'),
('Canva paid subscribers in India are declining. What''s wrong?', 'execution', 'medium', 'diagnosis'),
('Amazon DAU in India dropped 20%. Find the root cause.', 'execution', 'hard', 'diagnosis'),
('Your product caused a global outage. How would you handle it?', 'execution', 'hard', 'problem_solving'),
('Your defective product caused illness in children. How would you handle it?', 'execution', 'hard', 'problem_solving'),
('As eBay PM, checkout conversion is low. What would you do?', 'execution', 'medium', 'problem_solving'),
('YouTube recommended video engagement dropped. What metrics would you track?', 'execution', 'medium', 'diagnosis'),
('At ChatGPT, thumbs-down feedback on responses is rising. How would you identify the cause and fix it?', 'execution', 'hard', 'diagnosis'),
('Avg. comments per story on a news platform increased from 2 → 3 in 2 days. What are your hypotheses?', 'execution', 'medium', 'diagnosis'),
('Engagement in Microsoft OneDrive dropped. How would you investigate?', 'execution', 'medium', 'diagnosis'),

-- ============================================================
-- ESTIMATION (100) → estimation
-- ============================================================
('Calculate the number of queries answered by Google per second.', 'estimation', 'medium', 'estimation'),
('How many dentists are there in New York?', 'estimation', 'easy', 'estimation'),
('How do you decide how many cash registers you need for a new Walmart store?', 'estimation', 'medium', 'estimation'),
('Estimate the number of Uber rides.', 'estimation', 'easy', 'estimation'),
('Estimate the number of bicycles required to start a bike-sharing operation in a big city.', 'estimation', 'medium', 'estimation'),
('Estimate the number of Tesla Model 3s in California.', 'estimation', 'medium', 'estimation'),
('How many elevators should an average office building have?', 'estimation', 'easy', 'estimation'),
('How much storage space is required to host all the images of Google Street View?', 'estimation', 'hard', 'estimation'),
('How many passengers are in planes in the air at any given time in the U.S.A.?', 'estimation', 'medium', 'estimation'),
('How much revenue did Gmail make from ads in the USA last year?', 'estimation', 'hard', 'estimation'),
('Estimate the number of planes that are in the air in an hour.', 'estimation', 'medium', 'estimation'),
('How would you estimate the total number of cars right now on Highway 101 between San Francisco and Mountain View?', 'estimation', 'medium', 'estimation'),
('Estimate the number of WhatsApp chats occurring in India.', 'estimation', 'medium', 'estimation'),
('Estimate the total number of videos on YouTube.', 'estimation', 'medium', 'estimation'),
('What is the market size of toilet paper in the US?', 'estimation', 'medium', 'estimation'),
('How would you estimate Google AdSense revenue?', 'estimation', 'hard', 'estimation'),
('How much storage is required to store all of the images on Google Maps?', 'estimation', 'hard', 'estimation'),
('You run a grocery delivery service that delivers within 24 hours. How many trucks would you need to operate it?', 'estimation', 'hard', 'estimation'),
('Estimate the number of passengers arriving at San Francisco International Airport each day.', 'estimation', 'medium', 'estimation'),
('A company launched a new drug that eliminates the need for sleep. How would you price this drug?', 'estimation', 'hard', 'estimation'),
('Estimate the number of orders delivered by Swiggy per hour in India.', 'estimation', 'medium', 'estimation'),
('Estimate the number of Facebook users in India.', 'estimation', 'easy', 'estimation'),
('How many balls does it take to fill a 16×16 ft room?', 'estimation', 'medium', 'estimation'),
('What is the market for driverless cars in 2020?', 'estimation', 'hard', 'estimation'),
('Estimate when you will get a Tesla Model 3 if you make a reservation today.', 'estimation', 'medium', 'estimation'),
('Estimate the market size for Google Fi.', 'estimation', 'hard', 'estimation'),
('How many Pixel phones were sold by Google worldwide in the last 12 months?', 'estimation', 'medium', 'estimation'),
('How many airports are in the US and in the world?', 'estimation', 'easy', 'estimation'),
('Estimate the total storage capacity for all videos on YouTube.', 'estimation', 'hard', 'estimation'),
('How would you estimate how many people are watching YouTube in India right now?', 'estimation', 'medium', 'estimation'),
('Estimate the memory needed for Nest cameras for the fiscal year 2020.', 'estimation', 'hard', 'estimation'),
('Estimate the daily bandwidth consumed by YouTube globally.', 'estimation', 'hard', 'estimation'),
('How would you increase the revenue of Microsoft PowerPoint?', 'estimation', 'hard', 'estimation'),
('How much storage space do you need for Google Maps?', 'estimation', 'hard', 'estimation'),
('How many queries per second does Gmail get?', 'estimation', 'medium', 'estimation'),
('How much money is spent in the USA per year on gas?', 'estimation', 'medium', 'estimation'),
('How many pianists are there in New York City?', 'estimation', 'easy', 'estimation'),
('Estimate AWS''s total annual revenue.', 'estimation', 'hard', 'estimation'),
('How would you estimate the number of new users Amazon gets in a day?', 'estimation', 'medium', 'estimation'),
('Estimate the number of tube lights used in a big city (population 10 million).', 'estimation', 'medium', 'estimation'),
('How would you estimate the bandwidth of Gmail for a community on Mars?', 'estimation', 'hard', 'estimation'),
('How many apps are in the Apple App Store or Google Play Store?', 'estimation', 'medium', 'estimation'),
('Estimate the market size of Prime Video.', 'estimation', 'hard', 'estimation'),
('How much time do people spend waiting at traffic signals in the U.S. while in their vehicles?', 'estimation', 'medium', 'estimation'),
('Estimate how many trains operate in the NYC subway.', 'estimation', 'medium', 'estimation'),
('Estimate the cost of storing Google Photos content.', 'estimation', 'hard', 'estimation'),
('How would you estimate the number of mobile phones sold by Xiaomi in a day?', 'estimation', 'medium', 'estimation'),
('You created a new product to replace the mobile phone. How would you determine how many units to manufacture?', 'estimation', 'hard', 'estimation'),
('How many mobile phones are there in the world?', 'estimation', 'easy', 'estimation'),
('Estimate the total number of millennials who own homes in the U.S.', 'estimation', 'medium', 'estimation'),
('How many kindergarten teachers are there in the U.S.?', 'estimation', 'easy', 'estimation'),
('How much would it cost to set up citywide Wi-Fi in New York?', 'estimation', 'hard', 'estimation'),
('YouTube Premium (formerly YouTube Red) has 1.5% of the initial YouTube user base sign up. What is the lifetime revenue from those users?', 'estimation', 'hard', 'estimation'),
('How much revenue does Airbnb generate annually in India?', 'estimation', 'hard', 'estimation'),
('Estimate the number of drones necessary to complete all Amazon deliveries in NYC.', 'estimation', 'hard', 'estimation'),
('How many iPhones and Android phones are there in the world? (Assume everyone has only one phone.)', 'estimation', 'medium', 'estimation'),
('How many pizzas would you need to circle the Earth at the equator?', 'estimation', 'medium', 'estimation'),
('How many drones would be needed to deliver all of FedEx''s packages in the U.S.?', 'estimation', 'hard', 'estimation'),
('How much revenue does your favorite restaurant make each year?', 'estimation', 'easy', 'estimation'),
('Estimate the number of YouTube users.', 'estimation', 'easy', 'estimation'),
('How many calories are in a typical grocery-store item?', 'estimation', 'easy', 'estimation'),
('Estimate the number of Groups on Facebook.', 'estimation', 'medium', 'estimation'),
('Estimate the number of hotels in NYC.', 'estimation', 'medium', 'estimation'),
('How would you estimate the space required for Google Photos?', 'estimation', 'hard', 'estimation'),
('Estimate the bandwidth (bits/s) of a 747 crossing the Atlantic filled with CDs.', 'estimation', 'hard', 'estimation'),
('How many reviews are left on Amazon on a given Monday?', 'estimation', 'medium', 'estimation'),
('If you launch YouTube TV in San Francisco, how much bandwidth is required?', 'estimation', 'hard', 'estimation'),
('As an Amazon delivery PM, estimate how many face masks to stock in UK stores during COVID-19 lockdown.', 'estimation', 'hard', 'estimation'),
('How many drivers does Uber have in a medium-sized U.S. city?', 'estimation', 'medium', 'estimation'),
('Estimate the number of actual COVID-19 positive people in India today.', 'estimation', 'hard', 'estimation'),
('Estimate the weight of a 747 airplane.', 'estimation', 'medium', 'estimation'),
('Tesla claims zero maintenance will make auto garages obsolete — estimate U.S. jobs impacted in 5 and 10 years.', 'estimation', 'hard', 'estimation'),
('How many videos can you watch with 2 GB of data?', 'estimation', 'easy', 'estimation'),
('How much time is spent per day waiting for a human in automated systems in the U.S.?', 'estimation', 'medium', 'estimation'),
('Estimate the market size of an online flight-insurance business in the U.S.', 'estimation', 'hard', 'estimation'),
('How much money does India lose due to traffic congestion?', 'estimation', 'hard', 'estimation'),
('A biotech launches cell-based blood that reduces donation needs — how would you price it?', 'estimation', 'hard', 'estimation'),
('What is the market size of toilet paper in Canada?', 'estimation', 'medium', 'estimation'),
('Given G Suite revenue is $7B, how many G Suite users are there?', 'estimation', 'medium', 'estimation'),
('Estimate the annual budget Facebook needs to maintain Facebook Photos.', 'estimation', 'hard', 'estimation'),
('Estimate the total tolls collected in one day across all toll plazas in a country.', 'estimation', 'medium', 'estimation'),
('Google entering language learning: estimate the TAM for people who want to learn a new language.', 'estimation', 'hard', 'estimation'),
('Estimate monthly active users for Dropbox.', 'estimation', 'medium', 'estimation'),
('Pan-India 24-hour grocery delivery: estimate how many 1-ton trucks are needed.', 'estimation', 'hard', 'estimation'),
('Estimate airport waiting time; propose a moonshot to reduce it.', 'estimation', 'hard', 'estimation'),
('Estimate daily WhatsApp messages in India.', 'estimation', 'medium', 'estimation'),
('How many restaurants are in New York City?', 'estimation', 'easy', 'estimation'),
('How many windows are in New York City?', 'estimation', 'easy', 'estimation'),
('Estimate the number of EV charging stations in the U.S.', 'estimation', 'medium', 'estimation'),
('Estimate daily passengers passing through security at an airport of your choice.', 'estimation', 'medium', 'estimation'),
('How many articles does the average American read per month?', 'estimation', 'easy', 'estimation'),
('How many webcams were sold in the U.S. in 2020?', 'estimation', 'medium', 'estimation'),
('Estimate how many videos are uploaded to YouTube per day.', 'estimation', 'medium', 'estimation'),
('Estimate Airbnb''s annual U.S. revenue.', 'estimation', 'hard', 'estimation'),
('How much revenue could Google earn from driverless cars?', 'estimation', 'hard', 'estimation'),
('If Amazon raises Prime''s price, estimate incremental revenue (or loss).', 'estimation', 'hard', 'estimation'),
('Estimate the number of electric vehicles in Bangalore.', 'estimation', 'medium', 'estimation'),
('Estimate ad revenue for a photo-sharing social media app.', 'estimation', 'hard', 'estimation'),
('What is the market size of the U.K. art market?', 'estimation', 'medium', 'estimation'),
('Estimate the number of daily transactions handled by Visa worldwide.', 'estimation', 'hard', 'estimation'),

-- ============================================================
-- BEHAVIOURAL (100) → behavioral
-- ============================================================
('In layman terms, describe your day-to-day activities as a Product Manager.', 'behavioral', 'easy', 'behavioral'),
('How would you keep developers working on a product motivated and producing quality work?', 'behavioral', 'medium', 'behavioral'),
('What are you looking for in your next role?', 'behavioral', 'easy', 'behavioral'),
('You are a PM about to enter a product launch meeting with all stakeholders. How would you prepare?', 'behavioral', 'medium', 'behavioral'),
('If three top-priority items are requested for a release but engineering capacity is limited, and the client insists on all three, what will you do?', 'behavioral', 'hard', 'behavioral'),
('A senior client calls you early morning to complain that the B2B product is not working (with no details). How would you approach this?', 'behavioral', 'medium', 'behavioral'),
('A customer reported an issue with your .Net software in a public forum and threatened to switch platforms. How would you handle it?', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time you investigated a problem on your team and had to dig through multiple layers to figure it out. Who did you talk to and what information proved most valuable?', 'behavioral', 'medium', 'behavioral'),
('Where do you see yourself in 5 years?', 'behavioral', 'easy', 'behavioral'),
('Why should Amazon not hire you?', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time you had conflict with a team member or manager.', 'behavioral', 'medium', 'behavioral'),
('How do you prioritize Sales needs vs Engineering needs?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you influenced engineering to build a particular feature.', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time when you used data to influence or persuade people.', 'behavioral', 'medium', 'behavioral'),
('Describe a complex topic as if I were a high school student who knows nothing about it.', 'behavioral', 'easy', 'behavioral'),
('How do you know when to cut corners to get a product out the door?', 'behavioral', 'hard', 'behavioral'),
('How do you prioritize requirements?', 'behavioral', 'medium', 'behavioral'),
('How would you convince the Engineering team to build a very different product than they want to develop?', 'behavioral', 'hard', 'behavioral'),
('How would you make something significantly simpler for a customer?', 'behavioral', 'medium', 'behavioral'),
('How do you motivate a Product team?', 'behavioral', 'medium', 'behavioral'),
('You are the PM of a video conferencing app (pre-COVID). You ran a survey with 400,000 respondents: 40% gave a score of 2, and 40% gave a score of 4 (on a 1–5 scale). How would you use these results?', 'behavioral', 'hard', 'behavioral'),
('What is the most challenging project you have been on?', 'behavioral', 'medium', 'behavioral'),
('What kind of project would you like to work on?', 'behavioral', 'easy', 'behavioral'),
('Was there a time when you disagreed with your manager''s decision? How did it play out, and what happened in the end?', 'behavioral', 'medium', 'behavioral'),
('As a PM, which is your favorite team to work with and why?', 'behavioral', 'easy', 'behavioral'),
('Your Engineering Manager wants to work on a new feature, but you have no bandwidth. How will you handle it?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you made a product or process simpler for customers, with significant impact.', 'behavioral', 'medium', 'behavioral'),
('How did you handle communicating with various types of stakeholders on a recent project, and what did you find most effective?', 'behavioral', 'medium', 'behavioral'),
('Tell us about yourself and your career.', 'behavioral', 'easy', 'behavioral'),
('Have you ever disagreed with your Engineering counterparts? What did you do when a build decision did not align with your original vision?', 'behavioral', 'medium', 'behavioral'),
('How did you resolve conflict among different groups?', 'behavioral', 'medium', 'behavioral'),
('Describe the most significant continuous improvement project you''ve led. What was the catalyst, and how did you approach it?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a situation where things did not go as planned. What did you learn from it?', 'behavioral', 'medium', 'behavioral'),
('How do you prioritize technical debt against new features?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you gave a simple solution to a complex problem.', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time when you changed your decision in a meeting based on stakeholder input. What was the situation, and what convinced you?', 'behavioral', 'medium', 'behavioral'),
('YouTube traffic went down 5% — how would you report this issue to your manager?', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time you had to change the way you work.', 'behavioral', 'medium', 'behavioral'),
('Tell us about a time you had an idea your team was skeptical about. How did you convince them?', 'behavioral', 'medium', 'behavioral'),
('How would you motivate your team to align around your idea?', 'behavioral', 'medium', 'behavioral'),
('How do you motivate a team?', 'behavioral', 'medium', 'behavioral'),
('Provide an example of when you had to analyze a large amount of data and what insights you came up with.', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time when you were halfway to meeting your goal but had to pivot because the goal wasn''t right.', 'behavioral', 'hard', 'behavioral'),
('Can you tell me about a time when you had to deal with customer complaints?', 'behavioral', 'medium', 'behavioral'),
('What do you enjoy about being a PM? What do you not enjoy?', 'behavioral', 'easy', 'behavioral'),
('Some companies don''t think they need PMs. Even Google didn''t have them for a while. What''s your opinion?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time you built something from 0 to 1.', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you had to manage upwards (aligning senior stakeholders).', 'behavioral', 'hard', 'behavioral'),
('How do you deal with engineering challenges at your current job?', 'behavioral', 'medium', 'behavioral'),
('How will you communicate to your team that you made a mistake? What steps would you take?', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time when you faced a problem that had multiple possible solutions.', 'behavioral', 'medium', 'behavioral'),
('If you only had one engineering resource, where would you invest it: fixing a critical bug or shipping a critical feature?', 'behavioral', 'hard', 'behavioral'),
('How do you prioritize among competing features?', 'behavioral', 'hard', 'behavioral'),
('What is your superpower as a product manager?', 'behavioral', 'easy', 'behavioral'),
('What would you do if your product is not growing despite high-quality execution?', 'behavioral', 'hard', 'behavioral'),
('How do you handle missed deadlines or scope creep?', 'behavioral', 'medium', 'behavioral'),
('Share an example of a time when you empowered someone else.', 'behavioral', 'medium', 'behavioral'),
('You''re a PM at Walmart. How would you ensure the development team accurately estimates their work?', 'behavioral', 'hard', 'behavioral'),
('What is one career failure you faced? How did you deal with it?', 'behavioral', 'medium', 'behavioral'),
('What challenges in your previous role would you want to avoid in your new role?', 'behavioral', 'medium', 'behavioral'),
('How do you define and track leading vs lagging indicators in product strategy?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a product you worked on that failed.', 'behavioral', 'medium', 'behavioral'),
('As a PM at Google, describe a time when you made a data-driven product decision with limited information.', 'behavioral', 'hard', 'behavioral'),
('What makes a good PM?', 'behavioral', 'easy', 'behavioral'),
('Instagram''s recent profile grid update has sparked mixed feedback. As a Product Manager, how would you gather user insights and address negative feedback?', 'behavioral', 'medium', 'behavioral'),
('Your organization is undergoing a multi-year transformation. The product you''re leading has missed deadlines and faces cross-functional misalignment. How would you approach this, and what tools/methods would you use?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you launched or brought a product to market. What challenges did you face?', 'behavioral', 'medium', 'behavioral'),
('You''ve just been handed a 10% cut in the engineering budget. How would you still deliver on your roadmap?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you received harsh feedback. How did you react?', 'behavioral', 'medium', 'behavioral'),
('You are a senior PM for a data product. How would you prioritize between top customer requests, technical debt, and partner integration requirements?', 'behavioral', 'hard', 'behavioral'),
('You are working across multiple teams, and everyone needs your time. How will you manage your time and ensure product success?', 'behavioral', 'hard', 'behavioral'),
('You are responsible for a product that involves multiple teams, and you need to get them on board with your strategy. How will you do it?', 'behavioral', 'hard', 'behavioral'),
('Why should I hire you for this role?', 'behavioral', 'easy', 'behavioral'),
('How do you determine what customers want and need?', 'behavioral', 'medium', 'behavioral'),
('What''s a successful brainstorming session you conducted, and why do you consider it successful?', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time when you proactively identified an issue that would impact your team. How did you solve it?', 'behavioral', 'medium', 'behavioral'),
('Tell us about a situation where you had to earn the trust of a group to move forward.', 'behavioral', 'medium', 'behavioral'),
('Why do you want to work at Google?', 'behavioral', 'easy', 'behavioral'),
('You''re a Facebook PM and want to build a restaurant review and booking platform like Yelp. How would you pitch it to your leader? What data would you need? What goal would you set?', 'behavioral', 'hard', 'behavioral'),
('How would you put together a team?', 'behavioral', 'medium', 'behavioral'),
('How would you handle a situation where some workers believe they hold power over minorities in the workplace?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you had to challenge a teammate''s unpopular opinion.', 'behavioral', 'medium', 'behavioral'),
('Give an example of a mission or goal you didn''t think was achievable. How did you help your team try to achieve it? Were you successful?', 'behavioral', 'hard', 'behavioral'),
('Can you give us a few examples where you planned and conducted A/B tests?', 'behavioral', 'medium', 'behavioral'),
('Can you give me an example where you made changes to your app based on user feedback?', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time when you didn''t have enough data to make the right decision. What did you do, and was it correct in the end?', 'behavioral', 'hard', 'behavioral'),
('Tell me about a time when you used data to reach a conclusion.', 'behavioral', 'medium', 'behavioral'),
('How is your background and experience relevant to Fandom?', 'behavioral', 'easy', 'behavioral'),
('Tell me about a time when you had to mend your relationship with a colleague.', 'behavioral', 'medium', 'behavioral'),
('What is an example of asking 5 Whys to a customer?', 'behavioral', 'medium', 'behavioral'),
('Who was your most difficult customer? How did you handle them?', 'behavioral', 'medium', 'behavioral'),
('What would you do to make sure Facebook employees do not feel lonely?', 'behavioral', 'medium', 'behavioral'),
('Tell me about a time when you had to deal with ambiguity.', 'behavioral', 'medium', 'behavioral'),
('How do you know if your users are satisfied with your product?', 'behavioral', 'medium', 'behavioral'),
('Describe a difficult technical concept to me.', 'behavioral', 'easy', 'behavioral'),
('How do you deal with a person who believes in orthodoxy and does not believe in metrics or feature validation?', 'behavioral', 'hard', 'behavioral'),
('How would you handle a HIPPO (Highest Paid Person''s Opinion) situation and resolve conflicts between HIPPOs?', 'behavioral', 'hard', 'behavioral'),
('Provide an example where you took a product from inception to launch. What challenges did you face?', 'behavioral', 'hard', 'behavioral'),
('What makes you want to leave your current job, and why would Shopify keep you interested?', 'behavioral', 'medium', 'behavioral'),
('What makes you want to stay in Product Management long term?', 'behavioral', 'medium', 'behavioral')

on conflict do nothing;

-- ============================================================
-- WEEKLY PRACTICE PLAN (35 questions, 7 weeks × 5 weekdays)
-- Mondays: diagnosis/design  Tuesdays: estimation/design
-- Wednesdays: product_strategy  Thursdays: improve/estimate
-- Fridays: improve/design/strategy
-- ============================================================
insert into questions (question, category, difficulty, question_type) values

-- Week 01
('Design Disney+ for Kids.', 'product_sense', 'medium', 'design'),
('Estimate the total number of airplanes that take off from Mumbai airport.', 'estimation', 'medium', 'estimation'),
('Should Amazon get into the OTT market?', 'product_strategy', 'hard', 'strategy'),
('How would you improve Signal?', 'product_sense', 'medium', 'improve'),
('What is your favorite app and how would you improve it?', 'product_sense', 'easy', 'improve'),

-- Week 02
('Should Zomato start its own restaurant?', 'product_strategy', 'hard', 'strategy'),
('Estimate the number of refrigerators sold in 2021 in India.', 'estimation', 'medium', 'estimation'),
('Diagnose a 30% dip in Avg. Watch Time of Disney+.', 'execution', 'medium', 'diagnosis'),
('How would you improve Snapchat?', 'product_sense', 'medium', 'improve'),
('Design an app for artists to sell their art.', 'product_sense', 'medium', 'design'),

-- Week 03
('Diagnose a 20% drop in Cart Additions at Amazon.', 'execution', 'medium', 'diagnosis'),
('Design an app for renting items.', 'product_sense', 'easy', 'design'),
('How would you improve Apple Music?', 'product_sense', 'medium', 'improve'),
('Should YouTube start something like Clubhouse?', 'product_strategy', 'hard', 'strategy'),
('Estimate the number of footballs that can fit into a shipping container.', 'estimation', 'medium', 'estimation'),

-- Week 04
('Diagnose a 40% drop in Ride Bookings at Ola.', 'execution', 'medium', 'diagnosis'),
('Design a washing machine for kids.', 'product_sense', 'easy', 'design'),
('Should Microsoft enter the OTT market? (like Netflix/Prime)', 'product_strategy', 'hard', 'strategy'),
('Estimate the number of reviews written in the Swiggy App in one day.', 'estimation', 'medium', 'estimation'),
('How would you improve YouTube?', 'product_sense', 'medium', 'improve'),

-- Week 05
('Diagnose a 40% drop in messages sent on WhatsApp.', 'execution', 'medium', 'diagnosis'),
('Design a social network for kids.', 'product_sense', 'medium', 'design'),
('Should Flipkart sell gold on its platform?', 'product_strategy', 'hard', 'strategy'),
('Estimate the number of pizzas sold in India in a day.', 'estimation', 'easy', 'estimation'),
('Should Instagram discontinue the Threads app?', 'product_strategy', 'hard', 'strategy'),

-- Week 06
('Diagnose a 35% drop in orders on Blinkit/Zepto.', 'execution', 'medium', 'diagnosis'),
('Design Indeed for gig workers.', 'product_sense', 'medium', 'design'),
('Why do you think Salesforce bought Slack?', 'product_strategy', 'hard', 'strategy'),
('Estimate the number of smartphones sold in India in a year.', 'estimation', 'medium', 'estimation'),
('How would you improve revenue for Gaana?', 'product_sense', 'medium', 'improve'),

-- Week 07
('Diagnose a 50% drop in Outlook usage.', 'execution', 'hard', 'diagnosis'),
('Design an app to help senior citizens book health check-ups.', 'product_sense', 'medium', 'design'),
('Should Google enter the OTT market? (like Netflix/Prime)', 'product_strategy', 'hard', 'strategy'),
('What is the monthly revenue of a local gym in India?', 'estimation', 'easy', 'estimation'),
('How would you improve engagement for 1mg?', 'product_sense', 'medium', 'improve')

on conflict do nothing;
